echo "==========================================="
echo "Steps to build and run the project"
echo "============================================"
echo ""
echo "1. Create a .env using the template .env.template"
echo "2. Fill in the required environment variables in the .env file"
echo "3. Run the following command to build the dev env:"
echo "   docker compose up -d"
echo "GIVE IT A FEW MINUTES TO BUILD THE CONTAINER and install the dependencies"
echo ""
echo "You might need to wait for a while so that there is enough data collected to run the model"
echo ""
echo "4. Then just run the 'Reopen in container' command in the command palette (Ctrl+Shift+P) - as described in the README"

echo ""
echo "==========================================="